build: Add @types/node "src/i18n.ts(8,10): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`."