fix: Use Field(default_factory=list) not mutable []. chore: Use Sequence instead of List to satisfy mypy, since list entries are compatible but not identical.
error: Argument "borrower_documents" to "ApplicationWithRelations" has incompatible type "list[BorrowerDocument]"; expected "list[BorrowerDocumentBase]"  [arg-type]
note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
note: Consider using "Sequence" instead, which is covariant